```{r purl}
base.dir<-"C:/ALR/Models/conteStreamflow"
setwd(base.dir)
list.files()

# 
# ###danger danger
# file.remove("NAMESPACE")
# list.files()
# 
# setwd(file.path(base.dir,"r"))
# list.files()
# file.remove(list.files())
# list.files()
# 
# setwd(file.path(base.dir,"man"))
# list.files()
# file.remove(list.files())
# list.files()

```


```{r}
library(knitr)
setwd(base.dir)

```

```{r}
setwd(base.dir)


dirs<-c("rmd")
while (length(dirs)>0) {
     current.dir<-dirs[1]
     print(paste("=== directory ===", current.dir))
     
     rmd.files<-list.files(include.dirs = F, path = file.path(base.dir,current.dir))[
          grep(x = list.files(include.dirs = F, path = file.path(base.dir,current.dir)),".Rmd")]
     rmd.files<-gsub(".Rmd",replacement = "",x =rmd.files)
#      print(paste("      ",rmd.files))

     for (i in rmd.files){
          print(i)
          purl(paste0(base.dir,"/",current.dir,"/",i,".Rmd"),paste0(base.dir,"/r/",i,".R"))
          }

     dirs<-c(dirs,file.path(current.dir,
                            list.dirs(path = file.path(base.dir,current.dir),recursive = F,full.names = F) 
                            ))
     dirs<-dirs[-1]

}
rm(dirs, current.dir, rmd.files)
list.files(path = file.path(base.dir,"r"))
```

```{r}
library(devtools)
library(roxygen2)

```

```{r document}

setwd(base.dir)
document(clean = T)
```

```{r install package}
library(devtools)

# base.dir<-"C:/ALR/Models/conteStreamflow"
# install( pkg=base.dir )
# library(conteStreamflow)

```

```{r}

install_github( repo="conteStreamflow", username="anarosner" )

```

