
```{r}
#' @title Associate calendar dates a date object or numeric year, representing its water year.
#' @description Given a date, determines which water year it falls into, and assigns it a date corresponding to the last calendar day of the water year
#' @param d \code{vector of dates}  
#' @keywords dates, water year
#' @export

to_wateryear_date<-function(d) {
     require(lubridate)
     
     x<-data.frame(date=d,year=year(d),month=month(d))
     x[x$month>=10,"year"]<-x[x$month>=10,"year"]+1
     x$water.date<-as.Date(paste0(x$year,"/9/30"))
     return(x[,"water.date"])
}
```

```{r}
#' @title Associates calendar dates with a date representing its month.
#' @description Given a date, determines which month it falls into, and assigns the date corresponding to the first calendar day of the month. 
#' @param d \code{vector of dates}
#' @return \code{vector of dates}
#' @seealso \code{\link{conteStreamflow::to.water.year}}, \code{\link{conteStreamflow::to.season}}
#' @export

to_month_date<-function(d) {
     require(lubridate)
     return(as.Date(paste0(year(d),"/",month(d),"/1")))
}

```
